[theme]
primaryColor = "#0097A7"         # teal (buttons, highlights)
backgroundColor = "#FFFFFF"      # main background
secondaryBackgroundColor = "#F5FFFF"  # cards / panels
textColor = "#37474F"            # deep gray
font = "sans serif"

[logger]
level = "debug"

[client]
showErrorDetails = true


